const mongoose = require("mongoose");

const pitchSchema = new mongoose.Schema(
  {
    pitchName: {
      type: String,
      required: [true, "Pitch name required"],
      trim: true
    },
    pitchPrice: {
      type: Number,
      required: [true, "Price per hour is required"]
    },
    pitchLocation: {
      type: String,
      required: [true, "Pitch location is required"]
    },
    pitchDescription: {
      type: String,
      required: [true, "Pitch description is required"]
    },
    // 🚀 Stores the file path generated by Multer (e.g., 'uploads/171987654321-file.png')
    pitchImage: {
      type: String,
      required: [true, "Pitch image is required"] 
    },
    // 🚀 Relates the pitch to the owner who created it
    owner: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true
    }
  },
  { timestamps: true } // Automatically creates createdAt and updatedAt fields
);

module.exports = mongoose.model("Pitch", pitchSchema);