on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'choose environment'
        default: 'staging'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run script
        run: echo "workflow manual"

      - name: run in docker
        uses: docker://alpine:3.14
        with:
          entrypoint: /bin/sh 
          args: |
            -c "echo 'run command inside container'"

      - name: run last command
        run: echo "this is last command"
