name: Fullstack CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
    # تصحيح مكان الـ paths ليكون موازي للـ branches
    paths:
      - 'Front_end/**'
      - 'Back_end/**'

jobs:
  # 1. جوب الخاصة بالفرونت إند
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Frontend Deps
        working-directory: ./Front_end 
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./Front_end
        # 👇 لو عندك تيست اكتب npm test، لو عاوز تتأكد إن المشروع بيعمل Build صح اكتب:
        run: npm run build 

  # 2. جوب الخاصة بالباك إند
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Backend Deps
        working-directory: ./Back_end
        run: npm install

      - name: Run Backend Tests
        working-directory: ./Back_end
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        # 👇 بنشغل الملف بـ node العادية مش nodemon، وكمان بنخليه يتشيك على الـ syntax من غير ما يفضل معلق
        run: node app.js --version || node -v